title: Rainbow Reclamation
description: A Digital Hub For All Things Rainbow Warriors
google_analytics:
show_downloads: false
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/manoa-warrior-collective/
gems:
  - jekyll-mentions
  - jekyll-remote-theme